/*
SQLyog Community v13.1.7 (64 bit)
MySQL - 8.0.30 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param7`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('59930','5','0','0','47','0','100','0','0','0','0','0','0','','85','82238','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','On Quest accept - Self: Cast spell 82238 on Self');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param7`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('59930','5','2','0','48','0','100','0','0','0','0','0','0','','85','82238','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','On Quest accept - Self: Cast spell 82238 on Self');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param7`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('59930','5','1','0','49','0','100','0','0','0','0','0','0','','85','82238','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','On Quest accept - Self: Cast spell 82238 on Self');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param7`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('59930','5','3','0','50','0','100','0','0','0','0','0','0','','85','82238','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','On Quest accept - Self: Cast spell 82238 on Self');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param7`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('59930','5','4','0','51','0','100','0','0','0','0','0','0','','85','82238','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','On Quest accept - Self: Cast spell 82238 on Self');
